### ISSUE TITLE
[style] AllSites 수정 필요 사항

### ISSUE THREAD

**Issue by night-hawks-wake** [JuhyuckHong/bmwebmf#9]
.user
- 높이 키우기
- 테마색으로 변경 시도해보기

Logout (Btn)
- 색 변경 (highlight color)
- padding 변경

.display
- header와 간격 띄우기
- 상단 .sorting-adjust 요소 변경
      - '정렬'과 '사진 크기' 사이 간격 띄우기
      - '사진 크기'에 적용되는 버튼 변경 (icon 이용, 픽셀 크기의 좌우로 지정)
      - .thumbnails와 간격 띄우기
      - 반응형일 때 줄어드는 글자 크기 제한 걸기 (최소 크기 키우기)

.thumbnails
- .thumbnails-individual 요소 수정
     - img와 site-information 요소 간격 띄우기
     - img의 경우 아래까지 굴림으로 처리
     - site-information 요소의 박스 스타일 변경
           - 위 아래 Line 및 Padding
           - 현장 제목 글자가 가장 크게, 아래 다른 정보 글자 크기는 현장 제목보다 작게
           - 현장 제목 글씨 색 제거(bold는 보존)
           - 포인트 색 맞추기 (red -> tomato, green -> 메인 푸른색으로 변경, orange -> highlight 노란색으로 변경)
     - site-information 박스를 클릭했을 때도 사이트로 넘어갈 수 있도록 수정 (or hover시 화살표 color 변경 및 크기 변경으로 화살표 클릭하여 넘어가도록)

**Comment by JuhyuckHong** [comment]
😊
